<?php

namespace Sova\Admin\Helpers;

class DBHelper
{
    const fluentMethods = [
        "increments" => ['name' => 'string'],
		"tinyIncrements" => ['name' => 'string'],
		"smallIncrements" => ['name' => 'string'],
		"mediumIncrements" => ['name' => 'string'],
		"bigIncrements" => ['name' => 'string'],
		"char" => ['name' => 'string', 'length' => 'integer'],
		"string" => ['name' => 'string', 'length' => 'integer'],
		"text" => ['name' => 'string'],
		"mediumText" => ['name' => 'string'],
		"longText" => ['name' => 'string'],
		"integer" => ['name' => 'string', 'autoIncrement' => 'bool', 'unsigned' => 'bool'],
		"tinyInteger" => ['name' => 'string', 'autoIncrement' => 'bool', 'unsigned' => 'bool'],
		"smallInteger" => ['name' => 'string', 'autoIncrement' => 'bool', 'unsigned' => 'bool'],
		"mediumInteger" => ['name' => 'string', 'autoIncrement' => 'bool', 'unsigned' => 'bool'],
		"bigInteger" => ['name' => 'string', 'autoIncrement' => 'bool', 'unsigned' => 'bool'],
		"unsignedInteger" => ['name' => 'string', 'autoIncrement' => 'bool'],
		"unsignedTinyInteger" => ['name' => 'string', 'autoIncrement' => 'bool'],
		"unsignedSmallInteger" => ['name' => 'string', 'autoIncrement' => 'bool'],
		"unsignedMediumInteger" => ['name' => 'string', 'autoIncrement' => 'bool'],
		"unsignedBigInteger" => ['name' => 'string', 'autoIncrement' => 'bool'],
		"float" => ['name' => 'string', 'total' => 'integer', 'places' => 'integer'],
		"double" => ['name' => 'string', 'total' => 'integer', 'places' => 'integer'],
		"decimal" => ['name' => 'string', 'total' => 'integer', 'places' => 'integer'],
		"unsignedDecimal" => ['name' => 'string', 'total' => 'integer', 'places' => 'integer'],
		"boolean" => ['name' => 'string'],
		"enum" => ['allowed' => 'array'],
		"json" => ['name' => 'string'],
		"jsonb" => ['name' => 'string'],
		"date" => ['name' => 'string'],
		"dateTime" => ['name' => 'string', 'precision' => 'integer'],
		"dateTimeTz" => ['name' => 'string', 'precision' => 'integer'],
		"time" => ['name' => 'string', 'precision' => 'integer'],
		"timeTz" => ['name' => 'string', 'precision' => 'integer'],
		"timestamp" => ['name' => 'string', 'precision' => 'integer'],
		"timestampTz" => ['name' => 'string', 'precision' => 'integer'],
		"timestamps" => ['precision' => 'integer'],
		"nullableTimestamps" => ['precision' => 'integer'],
		"timestampsTz" => ['precision' => 'integer'],
		"softDeletes" => ['precision' => 'integer'],
		"softDeletesTz" => ['precision' => 'integer'],
		"year" => ['name' => 'string'],
		"binary" => ['name' => 'string'],
		"uuid" => ['name' => 'string'],
		"ipAddress" => ['name' => 'string'],
		"macAddress" => ['name' => 'string'],
		"geometry" => ['name' => 'string'],
		"point" => ['name' => 'string', 'srid' => 'integer'],
		"lineString" => ['name' => 'string'],
		"polygon" => ['name' => 'string'],
		"geometryCollection" => ['name' => 'string'],
		"multiPoint" => ['name' => 'string'],
		"multiLineString" => ['name' => 'string'],
		"multiPolygon" => ['name' => 'string'],
		"morphs" => ['name' => 'string'],
		"nullableMorphs" => ['name' => 'string'],
		"rememberToken" => [],
    ];
}