<?php

namespace Sova\Admin\Console;

use Illuminate\Console\GeneratorCommand;
use Symfony\Component\Console\Input\InputOption;

class MigrationMakeCommand extends GeneratorCommand
{
    protected $name = 'admin:make:migration';

    protected function getStub()
    {
        return __DIR__ . '/../../stubs/model.stub';
    }

    protected function getDefaultNamespace($rootNamespace)
    {
        return parent::getDefaultNamespace($rootNamespace) . '\Models'; // TODO: Change the autogenerated stub
    }

    protected function replaceClass($stub, $name)
    {
        $replace = [
            'DummyFields' => $this->buildFields(),
        ];

        $stub = str_replace(array_keys($replace), array_values($replace), $stub);

        return parent::replaceClass($stub, $name);
    }

    protected function buildFields()
    {

    }

    protected function getOptions()
    {
        return [
            ['fields', null, InputOption::VALUE_NONE],
        ];
    }
}